### ISSUE TITLE
Can I use this to make a Special EXE Compressor?

### ISSUE THREAD

**Issue by AraHaan** [cryptobiu/cryptopp#1]
So, I use to use Petite, That is fine except when I have to somehow encrypt the IL code in my .NET Assemblies. So, could I use this to somehow encrypt the .NET Code and somehow inject methods of telling it to how to decode the IL Code to memory making it work but yet also protected from ILSpy.

why? This is because I do not want my .NET Programs to easily be Reverse enginered with Crypto++ it could help me out a lot.

Sorry, for the question but it would be nice having a example of such ability and usage of Crypto++

**Comment by d3v1l401** [comment]
You can, but you need more knowledge than just what you think.
You need to know PE structures and how memory is generally handled, also, you need to know how to handle compiling settings for an optimized and/or better security.

By the way, there're some tutorials on the internet, but writing your own packer isn't the best idea unless you have a really interesting method and huge experience in the field, otherwise your packer would just result in another flop and you wouldn't have stopped anyone.

**Comment by AraHaan** [comment]
I do know the PE Format somewhat like where the code is generally in the ``.text`` or ``.data`` sections in most cases. As well as resources almost always in ``.rsrc`` unless the assemply only has 1 section.

**Comment by liorbiu** [comment]
Hi,

We are not the owner of Crypto++ and does not supply for this library.
Yo can read about Crypto++ at this [link](https://www.cryptopp.com/). 
You can check our c++ library for secure computation at [libscapi](https://github.com/cryptobiu/libscapi).
